import { state } from './app.js';
import { show, refresh, adminLogout } from './auth.js';
import { savePlan, deletePlan, saveExercise, deleteExercise, deletePlayer, saveAdminSettings } from './store.js';
import { esc, slug, normPhone } from './utils.js';

export async function renderAdmin(){ if(!state.currentAdmin){show('adminLogin');return} await refresh(); document.getElementById('settings').innerHTML=`<div class="row" style="justify-content:space-between"><h2>Správce</h2><button class="secondary" id="adminLogoutBtn">Odhlásit správce</button></div><h3>Nastavení správce</h3><div class="row"><div><label>Nové heslo správce</label><input id="newAdminPass" type="password"></div><div><label>Telefon správce</label><input id="adminPhone" value="${esc(state.admin.phone||'')}" type="tel"></div><button id="saveAdminBtn">Uložit</button><button class="secondary" id="goOverviewAll">Přehled všech hráčů</button></div><p id="adminMsg" class="muted"></p><h3>Tréninkové plány</h3><div id="plansSettings" class="scroll"></div><p><button id="addPlanBtn">+ Přidat plán</button></p><h3>Úprava cvičení</h3><div id="exerciseSettings"></div><p><button id="addExerciseBtn">+ Přidat cvičení</button></p><h3>Registrovaní hráči</h3><div id="playersSettings" class="scroll"></div>`; adminLogoutBtn.onclick=adminLogout; goOverviewAll.onclick=()=>show('overview'); saveAdminBtn.onclick=doSaveAdmin; addPlanBtn.onclick=addPlan; addExerciseBtn.onclick=addExercise; renderPlans(); renderExercises(); renderPlayers(); }
function renderPlans(){ plansSettings.innerHTML='<table><tr><th>Název</th><th>Od</th><th>Do</th><th>Aktivní</th><th>Akce</th></tr>'+state.plans.map(p=>`<tr><td><input id="pname_${p.id}" value="${esc(p.name)}"></td><td><input type="date" id="pstart_${p.id}" value="${esc(p.start)}"></td><td><input type="date" id="pend_${p.id}" value="${esc(p.end)}"></td><td><input type="checkbox" id="pactive_${p.id}" ${p.active?'checked':''}></td><td><button onclick="window.savePlanRow('${p.id}')">Uložit</button> <button class="danger" onclick="window.deletePlanRow('${p.id}')">Smazat</button></td></tr>`).join('')+'</table>'; }
function renderExercises(){ exerciseSettings.innerHTML=state.exercises.map(e=>`<div class="card" style="background:#f9fafb"><div class="row"><div><label>Název</label><input id="ename_${e.key}" value="${esc(e.name)}"></div><div><label>Plán</label><input id="etarget_${e.key}" value="${esc(e.target||'')}"></div><div><label>Jednotka</label><input id="eunit_${e.key}" value="${esc(e.unit||'')}"></div><button onclick="window.saveExerciseRow('${e.key}')">Uložit</button><button class="danger" onclick="window.deleteExerciseRow('${e.key}')">Smazat</button></div></div>`).join(''); }
function renderPlayers(){ if(!state.players.length){playersSettings.innerHTML='<p class="note">Zatím není registrován žádný hráč.</p>';return} playersSettings.innerHTML='<table><tr><th class="left">Hráč</th><th>Telefon</th><th>PIN</th><th>Akce</th></tr>'+state.players.map(p=>`<tr><td class="left">${esc(p.name)}</td><td>${esc(p.phone)}</td><td><b>${esc(p.pin)}</b></td><td><button class="danger" onclick="window.deletePlayerRow('${p.id}')">Smazat</button></td></tr>`).join('')+'</table>'; }
async function doSaveAdmin(){ let data={password:state.admin.password||'hclitvinov',phone:state.admin.phone||''}; if(newAdminPass.value.trim()) data.password=newAdminPass.value.trim(); if(adminPhone.value.trim()){let ph=normPhone(adminPhone.value); if(!ph){adminMsg.textContent='Telefon není ve správném formátu.';return} data.phone=ph;} await saveAdminSettings(data); adminMsg.textContent='Nastavení uloženo.'; }
async function addPlan(){ let id='plan_'+Date.now(); await savePlan({id,name:'Nový plán',note:'',start:'2026-09-01',end:'2026-09-30',status:'active',active:false}); renderAdmin(); }
async function addExercise(){ let key='cvik_'+Date.now(); let active=(state.plans.find(p=>p.active)||state.plans[0]).id; await saveExercise({key,name:'Nové cvičení',target:'',unit:'opakování',plans:[active]}); renderAdmin(); }
window.savePlanRow=async(id)=>{ let plan=state.plans.find(p=>p.id===id); let updated={...plan,name:document.getElementById('pname_'+id).value,start:document.getElementById('pstart_'+id).value,end:document.getElementById('pend_'+id).value,active:document.getElementById('pactive_'+id).checked}; if(updated.active){ for(const p of state.plans){ if(p.id!==id&&p.active) await savePlan({...p,active:false}); } } await savePlan(updated); renderAdmin(); };
window.deletePlanRow=async(id)=>{ if(confirm('Smazat plán?')){ await deletePlan(id); renderAdmin(); } };
window.saveExerciseRow=async(key)=>{ let e=state.exercises.find(x=>x.key===key); await saveExercise({...e,name:document.getElementById('ename_'+key).value,target:document.getElementById('etarget_'+key).value,unit:document.getElementById('eunit_'+key).value}); renderAdmin(); };
window.deleteExerciseRow=async(key)=>{ if(confirm('Smazat cvičení?')){ await deleteExercise(key); renderAdmin(); } };
window.deletePlayerRow=async(id)=>{ if(confirm('Smazat hráče?')){ await deletePlayer(id); renderAdmin(); } };
